---
#title: "BlackFriday_project"
#author: "Magdalena"
#date: "22 Maerz 2019"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
header-includes:
  \AtBeginDocument{\let\maketitle\relax}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Projektarbeit zu Algorithmik & Statistik für Data Science 2 Lab
 
##Black Friday - eine statistische Analyse der Verkaufszahlen \n

Christoph Rabensteiner: 1810837995 \n

Valentin Muhr: 1810837102 \n

Magdalena Breu: 1810837995 \n

Jochen Paul Hollich: 1810837475 \n


## Beschreibung des Datensatzes.  

Der Datensatz Black Friday enthält Daten über den Warenkorb von Kunden bei einem Onlineshop. Im Datensatz befinden sich 537577 Beobachtungen für 12 Variablen, u.a. Geschlecht, Alter, Beruf, Beziehungsstatus und Kaufkraft. Die Variablen Age, Occupation, City_Category, Stay_In_Current_City_Years Product_Categories sind als Faktoren codiert. Die genauen Definitionen der einzelnen Faktoren (z.B. City_Category A,B &C) sind nicht genau definiert.  

```{R, echo = F, results = 'hide'}
data <- read.csv("BlackFriday.csv")
summary(data)
hist(data$Purchase)
```

## Hintergrundinformationen zum Datensatz 

Der Datensatz wurde bereitgestellt durch einen Hackathon der Firma Analytics Vidhya  (https://datahack.analyticsvidhya.com/contest/black-friday/) und heruntergeladen über Kaggle.com  (https://www.kaggle.com/mehdidag/black-friday). 


## Die statistische Lernaufgabe 

Mit diesem Datensatz soll eine Customer Segmentierung vorgenommen werden, um so den einzelnen Kundengruppen gezielt z.B. Werbung einschalten zu können oder als Input für einen Report an die Geschäftsleitung. Unter anderem sind die folgenden Analysen vorgesehen:

        - Segmentierung der Customerbase mittles Clustering
        - Klassifizierung z.B. nach Stadt, Berufsgruppe etc. 
        - Regression: Vorhersage des Sale-Volumen für die jeweiligen Customer Segmente


## Gründe warum die statistische Lernaufgabe auf diesen Datensatz angewendet wird 

Ausser für den Abschluss dieses Projekts, haben wir uns für den Black Friday Datensatz entschieden, da alle von uns einen  wirtschaftlichen Hintergrund haben (Studium oder Beruf) und uns erhoffen, die Modelle, die wir erstellen auch verstehen und interpretieren koennen. 

Der Datensatz ist ein Beispiel für eine Transaktionsliste für einen Einzelhandelsshop. Der Shop moechte das Verhalten seiner Kunden zu ihren Produkten besser verstehen. Wir sind der Meinung, dass dies ein realistisches Szenario ist, welches wir auch spaeter in unserem beruflichen Werdegang gut gebrauchen koennen. So kann beispielsweise ein  


## Nachweis, dass die Daten in R geladen werden können 

```{R}
summary(data)
data[1:4,]
```

## Einfache Modellierung der Daten

Als einfaches Beispiel für die mögliche Modellierung der Black Friday Daten wird eine einfache lineare Regression auf die ersten 200 Datensätze gefittet. Die ersten 10 Predictions sind ausgegeben.

```{R,message = FALSE, warning = FALSE}
library(caret)
training <- data[1:200,]
training$Product_ID <- NULL

model_test <- train(
  Purchase ~ ., 
  data = training, 
  method = "lm", 
  preProc = c("center", "scale"),
  na.action = na.pass 
)

pred_test <- predict(model_test, training)
pred_test[1:10]

```



